# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blob.ui'
#
# Created: Thu Feb  7 10:25:26 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BlobForm(object):
    def setupUi(self, BlobForm):
        BlobForm.setObjectName(_fromUtf8("BlobForm"))
        BlobForm.resize(716, 415)
        self.horizontalLayout = QtGui.QHBoxLayout(BlobForm)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidgetBlob = QtGui.QTabWidget(BlobForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetBlob.sizePolicy().hasHeightForWidth())
        self.tabWidgetBlob.setSizePolicy(sizePolicy)
        self.tabWidgetBlob.setMinimumSize(QtCore.QSize(250, 0))
        self.tabWidgetBlob.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidgetBlob.setDocumentMode(False)
        self.tabWidgetBlob.setTabsClosable(False)
        self.tabWidgetBlob.setObjectName(_fromUtf8("tabWidgetBlob"))
        self.tabBlob = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabBlob.sizePolicy().hasHeightForWidth())
        self.tabBlob.setSizePolicy(sizePolicy)
        self.tabBlob.setObjectName(_fromUtf8("tabBlob"))
        self.groupBoxBlob = QtGui.QGroupBox(self.tabBlob)
        self.groupBoxBlob.setGeometry(QtCore.QRect(20, 20, 177, 231))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBoxBlob.sizePolicy().hasHeightForWidth())
        self.groupBoxBlob.setSizePolicy(sizePolicy)
        self.groupBoxBlob.setCheckable(False)
        self.groupBoxBlob.setObjectName(_fromUtf8("groupBoxBlob"))
        self.formLayoutBlob = QtGui.QFormLayout(self.groupBoxBlob)
        self.formLayoutBlob.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayoutBlob.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayoutBlob.setContentsMargins(2, -1, 2, -1)
        self.formLayoutBlob.setHorizontalSpacing(2)
        self.formLayoutBlob.setVerticalSpacing(6)
        self.formLayoutBlob.setObjectName(_fromUtf8("formLayoutBlob"))
        self.labelType = QtGui.QLabel(self.groupBoxBlob)
        self.labelType.setObjectName(_fromUtf8("labelType"))
        self.formLayoutBlob.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelType)
        self.labelTypeValue = QtGui.QLabel(self.groupBoxBlob)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTypeValue.setFont(font)
        self.labelTypeValue.setObjectName(_fromUtf8("labelTypeValue"))
        self.formLayoutBlob.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelTypeValue)
        self.checkBoxCompressed = QtGui.QCheckBox(self.groupBoxBlob)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCompressed.sizePolicy().hasHeightForWidth())
        self.checkBoxCompressed.setSizePolicy(sizePolicy)
        self.checkBoxCompressed.setCheckable(True)
        self.checkBoxCompressed.setObjectName(_fromUtf8("checkBoxCompressed"))
        self.formLayoutBlob.setWidget(1, QtGui.QFormLayout.SpanningRole, self.checkBoxCompressed)
        self.labelSize = QtGui.QLabel(self.groupBoxBlob)
        self.labelSize.setObjectName(_fromUtf8("labelSize"))
        self.formLayoutBlob.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelSize)
        self.labelTimeStamp = QtGui.QLabel(self.groupBoxBlob)
        self.labelTimeStamp.setObjectName(_fromUtf8("labelTimeStamp"))
        self.formLayoutBlob.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelTimeStamp)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayoutBlob.setItem(7, QtGui.QFormLayout.LabelRole, spacerItem)
        self.labelSizeValue = QtGui.QLabel(self.groupBoxBlob)
        self.labelSizeValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSizeValue.setObjectName(_fromUtf8("labelSizeValue"))
        self.formLayoutBlob.setWidget(4, QtGui.QFormLayout.SpanningRole, self.labelSizeValue)
        self.labelTimeStampValue = QtGui.QLabel(self.groupBoxBlob)
        self.labelTimeStampValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTimeStampValue.setObjectName(_fromUtf8("labelTimeStampValue"))
        self.formLayoutBlob.setWidget(6, QtGui.QFormLayout.SpanningRole, self.labelTimeStampValue)
        self.labelLen = QtGui.QLabel(self.groupBoxBlob)
        self.labelLen.setObjectName(_fromUtf8("labelLen"))
        self.formLayoutBlob.setWidget(8, QtGui.QFormLayout.LabelRole, self.labelLen)
        self.labelLenValue = QtGui.QLabel(self.groupBoxBlob)
        self.labelLenValue.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLenValue.setObjectName(_fromUtf8("labelLenValue"))
        self.formLayoutBlob.setWidget(9, QtGui.QFormLayout.SpanningRole, self.labelLenValue)
        self.tabWidgetBlob.addTab(self.tabBlob, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2.sizePolicy().hasHeightForWidth())
        self.tab_2.setSizePolicy(sizePolicy)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(0, 60, 211, 192))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidgetBlob.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidgetBlob)
        self.widgetViewer = QtGui.QWidget(BlobForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widgetViewer.sizePolicy().hasHeightForWidth())
        self.widgetViewer.setSizePolicy(sizePolicy)
        self.widgetViewer.setObjectName(_fromUtf8("widgetViewer"))
        self.horizontalLayout.addWidget(self.widgetViewer)

        self.retranslateUi(BlobForm)
        self.tabWidgetBlob.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(BlobForm)

    def retranslateUi(self, BlobForm):
        BlobForm.setWindowTitle(QtGui.QApplication.translate("BlobForm", "BLOB", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxBlob.setTitle(QtGui.QApplication.translate("BlobForm", "BLOB Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.labelType.setText(QtGui.QApplication.translate("BlobForm", "Type: ", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTypeValue.setText(QtGui.QApplication.translate("BlobForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCompressed.setText(QtGui.QApplication.translate("BlobForm", "Compressed", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSize.setText(QtGui.QApplication.translate("BlobForm", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTimeStamp.setText(QtGui.QApplication.translate("BlobForm", "TimeStamp:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSizeValue.setText(QtGui.QApplication.translate("BlobForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTimeStampValue.setText(QtGui.QApplication.translate("BlobForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLen.setText(QtGui.QApplication.translate("BlobForm", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLenValue.setText(QtGui.QApplication.translate("BlobForm", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetBlob.setTabText(self.tabWidgetBlob.indexOf(self.tabBlob), QtGui.QApplication.translate("BlobForm", "BLOB", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidgetBlob.setTabText(self.tabWidgetBlob.indexOf(self.tab_2), QtGui.QApplication.translate("BlobForm", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))

