# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtindi.ui'
#
# Created: Thu Feb  7 10:34:17 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PyQtIndi(object):
    def setupUi(self, PyQtIndi):
        PyQtIndi.setObjectName(_fromUtf8("PyQtIndi"))
        PyQtIndi.resize(800, 480)
        self.centralwidget = QtGui.QWidget(PyQtIndi)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.horizontalLayout_2.addWidget(self.mdiArea)
        PyQtIndi.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PyQtIndi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuWindows = QtGui.QMenu(self.menubar)
        self.menuWindows.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuWindows.setObjectName(_fromUtf8("menuWindows"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        PyQtIndi.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PyQtIndi)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PyQtIndi.setStatusBar(self.statusbar)
        self.dockWidgetServer = QtGui.QDockWidget(PyQtIndi)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidgetServer.sizePolicy().hasHeightForWidth())
        self.dockWidgetServer.setSizePolicy(sizePolicy)
        self.dockWidgetServer.setMinimumSize(QtCore.QSize(98, 123))
        self.dockWidgetServer.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockWidgetServer.setObjectName(_fromUtf8("dockWidgetServer"))
        self.dockWidgetContentsServer = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidgetContentsServer.sizePolicy().hasHeightForWidth())
        self.dockWidgetContentsServer.setSizePolicy(sizePolicy)
        self.dockWidgetContentsServer.setSizeIncrement(QtCore.QSize(0, 0))
        self.dockWidgetContentsServer.setObjectName(_fromUtf8("dockWidgetContentsServer"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContentsServer)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeViewServer = QtGui.QTreeView(self.dockWidgetContentsServer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.treeViewServer.sizePolicy().hasHeightForWidth())
        self.treeViewServer.setSizePolicy(sizePolicy)
        self.treeViewServer.setSizeIncrement(QtCore.QSize(0, 0))
        self.treeViewServer.setBaseSize(QtCore.QSize(0, 0))
        self.treeViewServer.setObjectName(_fromUtf8("treeViewServer"))
        self.verticalLayout.addWidget(self.treeViewServer)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.dockWidgetServer.setWidget(self.dockWidgetContentsServer)
        PyQtIndi.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidgetServer)
        self.dockWidgetMessages = QtGui.QDockWidget(PyQtIndi)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidgetMessages.sizePolicy().hasHeightForWidth())
        self.dockWidgetMessages.setSizePolicy(sizePolicy)
        self.dockWidgetMessages.setMinimumSize(QtCore.QSize(96, 121))
        self.dockWidgetMessages.setObjectName(_fromUtf8("dockWidgetMessages"))
        self.dockWidgetContentsMessages = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dockWidgetContentsMessages.sizePolicy().hasHeightForWidth())
        self.dockWidgetContentsMessages.setSizePolicy(sizePolicy)
        self.dockWidgetContentsMessages.setObjectName(_fromUtf8("dockWidgetContentsMessages"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContentsMessages)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.textBrowserMessages = QtGui.QTextBrowser(self.dockWidgetContentsMessages)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBrowserMessages.sizePolicy().hasHeightForWidth())
        self.textBrowserMessages.setSizePolicy(sizePolicy)
        self.textBrowserMessages.setObjectName(_fromUtf8("textBrowserMessages"))
        self.verticalLayout_2.addWidget(self.textBrowserMessages)
        self.dockWidgetMessages.setWidget(self.dockWidgetContentsMessages)
        PyQtIndi.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetMessages)
        self.actionServer_Manager = QtGui.QAction(PyQtIndi)
        self.actionServer_Manager.setObjectName(_fromUtf8("actionServer_Manager"))
        self.actionQuit = QtGui.QAction(PyQtIndi)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionIndi_Control_Panel = QtGui.QAction(PyQtIndi)
        self.actionIndi_Control_Panel.setObjectName(_fromUtf8("actionIndi_Control_Panel"))
        self.actionLogs_Messages = QtGui.QAction(PyQtIndi)
        self.actionLogs_Messages.setObjectName(_fromUtf8("actionLogs_Messages"))
        self.menuWindows.addAction(self.actionServer_Manager)
        self.menuWindows.addAction(self.actionIndi_Control_Panel)
        self.menuWindows.addAction(self.actionLogs_Messages)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())

        self.retranslateUi(PyQtIndi)
        QtCore.QMetaObject.connectSlotsByName(PyQtIndi)

    def retranslateUi(self, PyQtIndi):
        PyQtIndi.setWindowTitle(QtGui.QApplication.translate("PyQtIndi", "PyQtIndi", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindows.setTitle(QtGui.QApplication.translate("PyQtIndi", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("PyQtIndi", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetServer.setWindowTitle(QtGui.QApplication.translate("PyQtIndi", "Indi Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidgetMessages.setWindowTitle(QtGui.QApplication.translate("PyQtIndi", "Logs-Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.actionServer_Manager.setText(QtGui.QApplication.translate("PyQtIndi", "Server Manager...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("PyQtIndi", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIndi_Control_Panel.setText(QtGui.QApplication.translate("PyQtIndi", "Indi Control Panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogs_Messages.setText(QtGui.QApplication.translate("PyQtIndi", "Logs-Messages", None, QtGui.QApplication.UnicodeUTF8))

